name: update to hostinger
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- name: zip
    #  uses: montudor/action-zip@v0.1.0
    #  with:
    #    args: zip -qq -r bundle.zip ./
#    - name: deploy to hostinger
#      uses: wlixcc/SFTP-Deploy-Action@v1.0
#      with:
#        server: ''
#        username: ${{ secrets.FTP_UN }}
#        ssh_private_key: ${{ secrets.HOSTINGER_KEY }}
#        local_path: './'
#        remote_path: '/public_html'
#        args: '-o ConnectTimeout=5'
#        port: '21'
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_KEY }}
        ARGS: >-  
          -rltgoDzvO
          --exclude='.git'
        REMOTE_HOST: '156.67.72.169'
        REMOTE_USER: ${{ secrets.SSH_UN }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        TARGET: /public_html/
    #- name: Webhook
    #  uses: distributhor/workflow-webhook@v2
    #  with:
    #    webhook_url: "https://webhooks.hostinger.com/deploy/0d915e74d5858d96523e47ea03f0e03c"
        #json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
    #- name: Checkout
    #  uses: actions/checkout@v1
    #- name: Push site to Hostinger
    #  run: |

    #- name: zipLambdaFunction
    #  uses: montudor/action-zip@v0.1.0
    #  with:
    #    args: zip -qq -r bundle.zip ./ -x *.zip -x *.sh -x *.json -x *.env
