name: update to hostinger
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_PRIV }}
      run: |
        mkdir $HOME/.ssh
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/private_key
        scp -P 65002 -C -r -i $HOME/.ssh/private_key ./* u956362618@156.67.72.151:~/co_public/
